import type {
  ProductClassification,
  ProductComparison,
  ProductEmailDetail,
  ProductEmailSummary,
  ProductReview,
} from "../types/product";

const baseClassification: ProductClassification = {
  category: "document_comparison",
  confidence: 0.94,
  candidate_scores: { document_comparison: 0.94, new_si_request: 0.04, general_message: 0.02 },
  reason: "Email requests draft B/L verification against Shipping Instruction for booking.",
  reason_code: "DRAFT_BL_CHECK_REQUEST",
  evidence: [],
  conflict_detected: false,
  resolved_at_stage: "stage1",
  comparison_readiness: "READY_FOR_COMPARISON",
  classifier_version: "2.1.0",
  created_at: "2026-09-24T18:00:00Z",
};

const cleanComparison: ProductComparison = {
  state: "COMPLETED",
  mismatch_found: false,
  mismatched_fields: [],
  unresolved_fields: [],
  reason_code: "ALL_MATCH",
  message: "No mismatch detected.",
  fields: [
    {
      field: "shipper",
      si: { raw: "ACME Global Trading Ltd", canonical: "ACME Global Trading Ltd", normalized: "acme global trading ltd" },
      bl: { raw: "ACME Global Trading Ltd", canonical: "ACME Global Trading Ltd", normalized: "acme global trading ltd" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "consignee",
      si: { raw: "Pacific Horizon Logistics Pte Ltd", canonical: "Pacific Horizon Logistics Pte Ltd", normalized: "pacific horizon logistics pte ltd" },
      bl: { raw: "Pacific Horizon Logistics Pte Ltd", canonical: "Pacific Horizon Logistics Pte Ltd", normalized: "pacific horizon logistics pte ltd" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "notify_party",
      si: { raw: "Same as Consignee", canonical: "Same as Consignee", normalized: "same as consignee" },
      bl: { raw: "Same as Consignee", canonical: "Same as Consignee", normalized: "same as consignee" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "port_of_loading",
      si: { raw: "Port Klang, Malaysia (MYPKG)", canonical: "Port Klang, Malaysia", normalized: "port klang malaysia" },
      bl: { raw: "Port Klang, Malaysia", canonical: "Port Klang, Malaysia", normalized: "port klang malaysia" },
      status: "MATCH",
      reason_code: "L1_PORT_ALIAS_MATCH",
      evidence: [],
    },
    {
      field: "port_of_discharge",
      si: { raw: "Tanjung Priok, Jakarta, Indonesia (IDTPP)", canonical: "Tanjung Priok, Indonesia", normalized: "tanjung priok indonesia" },
      bl: { raw: "Tanjung Priok, Indonesia", canonical: "Tanjung Priok, Indonesia", normalized: "tanjung priok indonesia" },
      status: "MATCH",
      reason_code: "L1_PORT_ALIAS_MATCH",
      evidence: [],
    },
    {
      field: "container_count",
      si: { raw: "2 x 40'HC", canonical: 2, normalized: 2 },
      bl: { raw: "2 x 40'HC", canonical: 2, normalized: 2 },
      status: "MATCH",
      reason_code: "L1_NUMERIC_MATCH",
      evidence: [],
    },
    {
      field: "gross_weight_kg",
      si: { raw: "22,000.00 KG", canonical: 22000, normalized: 22000 },
      bl: { raw: "22,000 KG", canonical: 22000, normalized: 22000 },
      status: "MATCH",
      reason_code: "L1_NUMERIC_MATCH",
      evidence: [],
    },
  ],
};

const mismatchComparison: ProductComparison = {
  state: "COMPLETED",
  mismatch_found: true,
  mismatched_fields: ["container_count", "gross_weight_kg"],
  unresolved_fields: ["notify_party"],
  reason_code: "MISMATCH_DETECTED",
  message: "2 fields mismatched (Container Count, Gross Weight), 1 field unresolved (Notify Party).",
  fields: [
    {
      field: "shipper",
      si: { raw: "ACME Global Trading Ltd", canonical: "ACME Global Trading Ltd", normalized: "acme global trading ltd" },
      bl: { raw: "ACME Global Trading Ltd", canonical: "ACME Global Trading Ltd", normalized: "acme global trading ltd" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "consignee",
      si: { raw: "Pacific Horizon Logistics Pte Ltd", canonical: "Pacific Horizon Logistics Pte Ltd", normalized: "pacific horizon logistics pte ltd" },
      bl: { raw: "Pacific Horizon Logistics Pte Ltd", canonical: "Pacific Horizon Logistics Pte Ltd", normalized: "pacific horizon logistics pte ltd" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "notify_party",
      si: { raw: "Apex Customs Brokerage Inc.", canonical: "Apex Customs Brokerage Inc.", normalized: "apex customs brokerage inc" },
      bl: { raw: null, canonical: null, normalized: null },
      status: "UNRESOLVED",
      reason_code: "FIELD_MISSING_IN_BL",
      evidence: [],
    },
    {
      field: "port_of_loading",
      si: { raw: "Port Klang, Malaysia", canonical: "Port Klang, Malaysia", normalized: "port klang malaysia" },
      bl: { raw: "Port Klang, Malaysia", canonical: "Port Klang, Malaysia", normalized: "port klang malaysia" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "port_of_discharge",
      si: { raw: "Tanjung Priok, Indonesia", canonical: "Tanjung Priok, Indonesia", normalized: "tanjung priok indonesia" },
      bl: { raw: "Tanjung Priok, Indonesia", canonical: "Tanjung Priok, Indonesia", normalized: "tanjung priok indonesia" },
      status: "MATCH",
      reason_code: "L0_EXACT_MATCH",
      evidence: [],
    },
    {
      field: "container_count",
      si: { raw: "2 x 40'HC", canonical: 2, normalized: 2 },
      bl: { raw: "3 x 40'HC", canonical: 3, normalized: 3 },
      status: "MISMATCH",
      reason_code: "VALUE_DIFFERENT",
      evidence: [],
    },
    {
      field: "gross_weight_kg",
      si: { raw: "22,000.00 KG", canonical: 22000, normalized: 22000 },
      bl: { raw: "24,850.00 KG", canonical: 24850, normalized: 24850 },
      status: "MISMATCH",
      reason_code: "VALUE_DIFFERENT",
      evidence: [],
    },
  ],
};

const mismatchSummary: ProductEmailSummary = {
  id: "case-demo-mismatch-001",
  external_message_id: "<bkg20240501-draft-bl@ocean-carrier.com>",
  source_type: "outlook",
  sender: "carrier-docs@ocean-carrier.com",
  subject: "Draft BL for BKG-20240501 for checking (ACME Global)",
  received_at: "2026-09-24T18:15:00Z",
  created_at: "2026-09-24T18:15:20Z",
  processing_status: "COMPLETED",
  attachment_count: 2,
  category: "document_comparison",
  classification_confidence: 0.96,
  comparison_readiness: "READY_FOR_COMPARISON",
  comparison_state: "COMPLETED",
  mismatch_count: 2,
  unresolved_count: 1,
  needs_review: true,
  review_id: "rev-demo-001",
  review_status: "OPEN",
  review_reason: "COMPARISON_UNRESOLVED",
  lifecycle: {
    lifecycle_status: "ACTIVE",
    outlook_read_state: "UNREAD",
    outlook_categories: ["BL_COMPARISON", "ACTION_REQUIRED"],
    outlook_folder_id: "inbox",
    outlook_archived: false,
    last_outlook_sync_at: "2026-09-24T18:16:00Z",
    outlook_sync_error: null,
    deleted_at: null,
    restored_at: null,
  },
};

const mismatchReview: ProductReview = {
  id: "rev-demo-001",
  email_id: "case-demo-mismatch-001",
  email: mismatchSummary,
  document_id: "doc-draft-bl-001",
  field: "notify_party",
  reason_code: "COMPARISON_UNRESOLVED",
  reason_text: "Draft BL is missing Notify Party. SI specifies Apex Customs Brokerage Inc.",
  status: "OPEN",
  case_origin: "ACTIVE",
  reviewer_name: null,
  confidence: 0.91,
  evidence: [],
  comparison: mismatchComparison,
  resolutions: [],
  ai_suggestions: [
    {
      id: "sug-demo-001",
      human_review_case_id: "rev-demo-001",
      mode: "ACTIONABLE_SUGGESTION",
      message: "Draft BL is missing Notify Party. SI provides Apex Customs Brokerage Inc.",
      document_side: "BL",
      field: "notify_party",
      current_value: null,
      suggested_value: "Apex Customs Brokerage Inc.",
      confidence: 0.94,
      reason: "SI explicitly states Notify Party: Apex Customs Brokerage Inc. Draft BL field is empty.",
      evidence_refs: ["SI Page 1: Notify Party: Apex Customs Brokerage Inc."],
      provider_name: "gemini",
      provider_model: "gemini-1.5-pro",
      status: "PENDING",
      created_at: "2026-09-24T18:15:35Z",
    },
  ],
  created_at: "2026-09-24T18:15:30Z",
};

export const demoCases: Record<string, { label: string; badge: string; detail: ProductEmailDetail }> = {
  mismatchReview: {
    label: "Mismatch & Review",
    badge: "2 Mismatches",
    detail: {
      email: mismatchSummary,
      body: "Dear HolyShip Ops,\n\nPlease find attached the draft Bill of Lading for booking BKG-20240501. Kindly check against your SI and advise confirmation or revisions.\n\nBest regards,\nOcean Carrier Customer Support",
      recipients: ["ops@holyship.com"],
      content_hash: "sha256-demo-mismatch-abc",
      attachments: [
        {
          id: "att-001",
          filename: "SI_BKG20240501_Final.pdf",
          content_type: "application/pdf",
          external_attachment_id: "att-si-001",
          retrieval_status: "RETRIEVED",
          retrieval_reason_code: null,
          content_sha256: "sha256-si-001",
        },
        {
          id: "att-002",
          filename: "Draft_BL_BKG20240501.pdf",
          content_type: "application/pdf",
          external_attachment_id: "att-bl-001",
          retrieval_status: "RETRIEVED",
          retrieval_reason_code: null,
          content_sha256: "sha256-bl-001",
        },
      ],
      classification: baseClassification,
      documents: [],
      comparison: mismatchComparison,
      timeline: [
        {
          id: "tl-001",
          event_type: "EMAIL_INGESTED",
          status: "COMPLETED",
          details: { source: "outlook_addin_sync" },
          created_at: "2026-09-24T18:15:20Z",
        },
        {
          id: "tl-002",
          event_type: "CLASSIFIED",
          status: "COMPLETED",
          details: { category: "document_comparison", confidence: 0.96 },
          created_at: "2026-09-24T18:15:22Z",
        },
        {
          id: "tl-003",
          event_type: "COMPARED",
          status: "COMPLETED",
          details: { mismatch_count: 2, unresolved_count: 1 },
          created_at: "2026-09-24T18:15:28Z",
        },
      ],
      review: [mismatchReview],
      resolutions: [
        {
          id: "res-001",
          email_id: "case-demo-mismatch-001",
          review_id: "rev-demo-001",
          field: "container_count",
          current_value: 3,
          suggested_value: 2,
          confidence: 0.92,
          reason: "SI explicitly requests 2 x 40'HC; Draft BL appears to include an erroneous extra container.",
          explanation: "Draft BL shows 3 containers while the customer Shipping Instruction specifies 2 units.",
          attempted: true,
          applied: false,
          created_at: "2026-09-24T18:15:35Z",
        },
        {
          id: "res-002",
          email_id: "case-demo-mismatch-001",
          review_id: "rev-demo-001",
          field: "gross_weight_kg",
          current_value: 24850,
          suggested_value: 22000,
          confidence: 0.89,
          reason: "Weight difference aligns with container count discrepancy.",
          explanation: "SI gross weight is 22,000 KG. Draft BL weight 24,850 KG should be reverted to SI reference.",
          attempted: true,
          applied: false,
          created_at: "2026-09-24T18:15:35Z",
        },
      ],
      outlook_workflow: {
        email_id: "case-demo-mismatch-001",
        status: "DRAFT_READY",
        summary: "Mismatches detected in Container Count (SI: 2 vs BL: 3) and Gross Weight (SI: 22,000 KG vs BL: 24,850 KG). Missing Notify Party on BL.",
        key_points: [
          "Request amendment of Container Count from 3 x 40'HC to 2 x 40'HC per SI",
          "Update Gross Weight from 24,850 KG to 22,000 KG",
          "Insert Notify Party: Apex Customs Brokerage Inc.",
        ],
        draft: "Dear Carrier Documentation Team,\n\nThank you for providing the draft B/L for booking BKG-20240501. Upon verification against our Shipping Instruction, please revise the following items:\n\n1. Container Count: Please amend from 3 x 40'HC to 2 x 40'HC.\n2. Gross Weight: Please correct to 22,000.00 KG (currently showing 24,850.00 KG).\n3. Notify Party: Please insert 'Apex Customs Brokerage Inc.' as per SI.\n\nPlease provide an amended draft once ready.\n\nThank you,\nHolyShip Operations",
        last_instruction: null,
        sent_at: null,
        updated_at: "2026-09-24T18:16:00Z",
      },
    },
  },

  cleanMatch: {
    label: "Clean Match",
    badge: "All 7 Match",
    detail: {
      email: {
        ...mismatchSummary,
        id: "case-demo-clean-002",
        external_message_id: "<bkg20240502-approved@ocean-carrier.com>",
        subject: "Draft BL for BKG-20240502 - Recheck Confirmed",
        mismatch_count: 0,
        unresolved_count: 0,
        needs_review: false,
        review_id: null,
        review_status: null,
        review_reason: null,
        lifecycle: {
          lifecycle_status: "ACTIVE",
          outlook_read_state: "READ",
          outlook_categories: ["BL_COMPARISON", "VERIFIED"],
          outlook_folder_id: "inbox",
          outlook_archived: false,
          last_outlook_sync_at: "2026-09-24T18:20:00Z",
          outlook_sync_error: null,
          deleted_at: null,
          restored_at: null,
        },
      },
      body: "Attached is the corrected draft BL for BKG-20240502. All previous comments incorporated.",
      recipients: ["ops@holyship.com"],
      content_hash: "sha256-demo-clean-xyz",
      attachments: [
        {
          id: "att-003",
          filename: "SI_BKG20240502.pdf",
          content_type: "application/pdf",
          external_attachment_id: "att-si-002",
          retrieval_status: "RETRIEVED",
          retrieval_reason_code: null,
          content_sha256: "sha256-si-002",
        },
        {
          id: "att-004",
          filename: "Draft_BL_BKG20240502_Final.pdf",
          content_type: "application/pdf",
          external_attachment_id: "att-bl-002",
          retrieval_status: "RETRIEVED",
          retrieval_reason_code: null,
          content_sha256: "sha256-bl-002",
        },
      ],
      classification: baseClassification,
      documents: [],
      comparison: cleanComparison,
      timeline: [],
      review: [],
      resolutions: [],
      outlook_workflow: {
        email_id: "case-demo-clean-002",
        status: "VERIFIED",
        summary: "All 7 canonical fields matched the reference Shipping Instruction exactly.",
        key_points: ["All fields verified", "Draft BL approved without amendments"],
        draft: "Dear Carrier Team,\n\nThe draft B/L for BKG-20240502 has been verified and confirmed. Please proceed to issue the Original / Sea Waybill.\n\nThank you,\nHolyShip Operations",
        last_instruction: null,
        sent_at: null,
        updated_at: "2026-09-24T18:20:00Z",
      },
    },
  },

  deletedInOutlook: {
    label: "Deleted in Outlook (Sync Demo)",
    badge: "DELETED",
    detail: {
      email: {
        ...mismatchSummary,
        id: "case-demo-deleted-003",
        subject: "Cancelled: Draft BL for BKG-20240503 (Moved to Trash)",
        lifecycle: {
          lifecycle_status: "DELETED",
          outlook_read_state: "READ",
          outlook_categories: ["BL_COMPARISON"],
          outlook_folder_id: "deleted_items",
          outlook_archived: false,
          last_outlook_sync_at: "2026-09-24T18:22:00Z",
          outlook_sync_error: null,
          deleted_at: "2026-09-24T18:21:45Z",
          restored_at: null,
        },
      },
      body: "Email was deleted by user in Outlook mailbox.",
      recipients: ["ops@holyship.com"],
      content_hash: "sha256-demo-deleted",
      attachments: [],
      classification: baseClassification,
      documents: [],
      comparison: mismatchComparison,
      timeline: [
        {
          id: "tl-009",
          event_type: "OUTLOOK_RECONCILED",
          status: "COMPLETED",
          details: { lifecycle_status: "DELETED", folder: "deleted_items" },
          created_at: "2026-09-24T18:22:00Z",
        },
      ],
      review: [mismatchReview],
      resolutions: [],
    },
  },
};
