"""Single authoritative constants for deterministic classification."""
SUBJECT_WEIGHT = 0.7
BODY_WEIGHT = 1.0
ATTACHMENT_METADATA_WEIGHT = 0.3
STAGE1_CONFIDENCE_THRESHOLD = 0.80
STAGE1_MARGIN_THRESHOLD = 0.25
STAGE2_SUBJECT_WEIGHT = 0.5
STAGE2_BODY_WEIGHT = 1.5
STAGE2_RESOLUTION_THRESHOLD = 0.65
STAGE2_MARGIN_THRESHOLD = 0.15
