import type {
  EmailQueuePage,
  HumanReviewPage,
  ProductEmailDetail,
  ProductSummary,
} from "../api/types";

export const demoSummary: ProductSummary = {
  total_emails: 128,
  status_counts: {
    COMPLETED: 84,
    AWAITING_DOCUMENTS: 12,
    BLOCKED: 25,
    FAILED: 7,
  },
  needs_review_count: 25,
  comparison_ready_count: 62,
  mismatch_count: 9,
  unresolved_count: 18,
};

export const demoQueue: EmailQueuePage = {
  total: 3,
  skip: 0,
  limit: 20,
  items: [
    {
      id: "11111111-1111-4111-8111-111111111111",
      external_message_id: "demo-clean",
      source_type: "STATIC_BUNDLE",
      sender: "ops@averis.example",
      subject: "Draft BL checked against SI",
      received_at: "2026-09-21T09:12:00+08:00",
      created_at: "2026-09-21T09:13:00+08:00",
      processing_status: "COMPLETED",
      attachment_count: 2,
      category: "document_comparison",
      classification_confidence: 0.96,
      comparison_readiness: "READY_FOR_COMPARISON",
      comparison_state: "COMPLETED",
      mismatch_count: 0,
      unresolved_count: 0,
      needs_review: false,
      review_status: null,
      review_reason: null,
    },
    {
      id: "22222222-2222-4222-8222-222222222222",
      external_message_id: "demo-mismatch",
      source_type: "STATIC_BUNDLE",
      sender: "customer@example.com",
      subject: "Please verify draft BL details",
      received_at: "2026-09-21T10:22:00+08:00",
      created_at: "2026-09-21T10:23:00+08:00",
      processing_status: "COMPLETED",
      attachment_count: 2,
      category: "document_comparison",
      classification_confidence: 0.91,
      comparison_readiness: "READY_FOR_COMPARISON",
      comparison_state: "COMPLETED",
      mismatch_count: 1,
      unresolved_count: 0,
      needs_review: false,
      review_status: null,
      review_reason: null,
    },
    {
      id: "33333333-3333-4333-8333-333333333333",
      external_message_id: "demo-awaiting",
      source_type: "STATIC_BUNDLE",
      sender: "shipper@example.com",
      subject: "Send draft BL for checking once available",
      received_at: "2026-09-21T11:02:00+08:00",
      created_at: "2026-09-21T11:04:00+08:00",
      processing_status: "AWAITING_DOCUMENTS",
      attachment_count: 0,
      category: "document_comparison",
      classification_confidence: 0.88,
      comparison_readiness: "AWAITING_DOCUMENTS",
      comparison_state: null,
      mismatch_count: 0,
      unresolved_count: 0,
      needs_review: false,
      review_status: null,
      review_reason: null,
    },
  ],
};

export const demoDetail: ProductEmailDetail = {
  email: demoQueue.items[1],
  body: "Please check the draft BL against the attached SI.",
  recipients: ["shipping@holyship.example"],
  content_hash: "demo",
  attachments: [
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      filename: "SI.pdf",
      content_type: "application/pdf",
      external_attachment_id: null,
      retrieval_status: "RETRIEVED",
      retrieval_reason_code: null,
      content_sha256: "sha-si",
    },
    {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      filename: "Draft-BL.pdf",
      content_type: "application/pdf",
      external_attachment_id: null,
      retrieval_status: "RETRIEVED",
      retrieval_reason_code: null,
      content_sha256: "sha-bl",
    },
  ],
  classification: {
    category: "document_comparison",
    confidence: 0.91,
    candidate_scores: { document_comparison: 0.91 },
    reason: "Body asks to check draft BL against SI.",
    reason_code: "BODY_EXPLICIT_COMPARE_REQUEST",
    evidence: [],
    conflict_detected: false,
    resolved_at_stage: "stage1",
    comparison_readiness: "READY_FOR_COMPARISON",
    classifier_version: "demo",
    created_at: "2026-09-21T10:23:00+08:00",
  },
  documents: [],
  comparison: {
    state: "COMPLETED",
    mismatch_found: true,
    mismatched_fields: ["container_count"],
    unresolved_fields: [],
    reason_code: "DEFINITE_MISMATCH",
    message: "Mismatch detected.",
    fields: [
      {
        field: "shipper",
        si: { raw: "Averis Logistics", canonical: "Averis Logistics", normalized: "averis logistics" },
        bl: { raw: "Averis Logistics", canonical: "Averis Logistics", normalized: "averis logistics" },
        status: "MATCH",
        reason_code: "L0_MATCH",
        evidence: [],
      },
      {
        field: "consignee",
        si: { raw: "Global Buyer Sdn Bhd", canonical: "Global Buyer Sdn Bhd", normalized: "global buyer sdn bhd" },
        bl: { raw: "Global Buyer Sdn Bhd", canonical: "Global Buyer Sdn Bhd", normalized: "global buyer sdn bhd" },
        status: "MATCH",
        reason_code: "L0_MATCH",
        evidence: [],
      },
      {
        field: "notify_party",
        si: { raw: "Same as consignee", canonical: "Same as consignee", normalized: "same as consignee" },
        bl: { raw: "Same as consignee", canonical: "Same as consignee", normalized: "same as consignee" },
        status: "MATCH",
        reason_code: "L0_MATCH",
        evidence: [],
      },
      {
        field: "port_of_loading",
        si: { raw: "Port Klang", canonical: "Port Klang", normalized: "port klang" },
        bl: { raw: "Port Klang", canonical: "Port Klang", normalized: "port klang" },
        status: "MATCH",
        reason_code: "L0_MATCH",
        evidence: [],
      },
      {
        field: "port_of_discharge",
        si: { raw: "Singapore", canonical: "Singapore", normalized: "singapore" },
        bl: { raw: "Singapore", canonical: "Singapore", normalized: "singapore" },
        status: "MATCH",
        reason_code: "L0_MATCH",
        evidence: [],
      },
      {
        field: "container_count",
        si: { raw: "3 containers", canonical: 3, normalized: 3 },
        bl: { raw: "4 containers", canonical: 4, normalized: 4 },
        status: "MISMATCH",
        reason_code: "VALUE_DIFFERENT",
        evidence: [],
      },
      {
        field: "gross_weight_kg",
        si: { raw: "22,000 KG", canonical: 22000, normalized: 22000 },
        bl: { raw: "22000 kg", canonical: 22000, normalized: 22000 },
        status: "MATCH",
        reason_code: "L1_WEIGHT_MATCH",
        evidence: [],
      },
    ],
  },
  timeline: [
    {
      id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
      old_status: "COMPARING",
      new_status: "COMPLETED",
      reason_code: "COMPARISON_COMPLETED",
      created_at: "2026-09-21T10:25:00+08:00",
    },
  ],
  review: [],
  resolutions: [],
};

export const demoHumanReview: HumanReviewPage = {
  total: 1,
  skip: 0,
  limit: 50,
  items: [
    {
      id: "99999999-9999-4999-8999-999999999999",
      email_id: demoQueue.items[1].id,
      email: demoQueue.items[1],
      document_id: null,
      field: "container_count",
      reason_code: "COMPARISON_UNRESOLVED",
      reason_text: "Container count requires review.",
      status: "OPEN",
      case_origin: "ACTIVE",
      confidence: 0.72,
      evidence: [],
      comparison: demoDetail.comparison,
      priority: "HIGH",
      presentation_title: "One or more document fields could not be verified",
      human_explanation: "The SI and BL evidence was not sufficient to determine one or more field values confidently. Affected fields: Container Count.",
      affected_fields: ["container_count"],
      affected_area: "Document fields",
      suggested_action: "Review the unresolved fields",
      semantic_style: "attention",
      age_minutes: 12,
      resolutions: [],
      created_at: "2026-09-21T10:25:00+08:00",
    },
  ],
};
